name: 'Checkov'

on:
  push:
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: 'Checkov'

    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Checkov Github Action
      uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # v12.1347.0
      with:
        directory: terraform
        quiet: true
        soft_fail: true
        framework: terraform
        var_file: terraform/example.tfvars
        output_format: sarif
        output_file_path: results.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@4e94bd11f71e507f7f87df81788dff88d1dacbfb # v2.23.5

      if: success() || failure()
      with:
        sarif_file: results.sarif