name: 'Helm Publish'

on:
  push:
    branches: [ 'main', '1.2.0' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set environment variables
      id: set-variable
      run: |
        echo "VERSION=$(yq -r .version ./chart/Chart.yaml)" >> "$GITHUB_OUTPUT"

    - name: Env variable output
      id: test-variable
      run: |
        echo ${{ steps.set-variable.outputs.VERSION }}

    - name: Update Helm dependencies
      run: |
        helm dependency update ./chart

    - name: Lint Helm chart
      run: |
        helm lint ./chart

    - name: Login to GitHub Container Registry
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Package and push helm chart
      run: |
        helm package ./chart --version ${{ steps.set-variable.outputs.VERSION }}
        helm push ./linea-dev-${{ steps.set-variable.outputs.VERSION }}.tgz oci://ghcr.io/${{ github.actor }}
